### ISSUE TITLE
should return non zero code when test fail

### ISSUE THREAD

**Issue by pinage404** [nix-community/nixt#11]
I just discovered this unit test tool

I'm trying it with this dummy program

```nix
{ nixt }:

nixt.mkSuites {
  "Hello" = {
    "world" = hello == "Hello world";
  };
}
```

```sh
nixt tests && echo "everything is good" || echo "something is bad"
```

```
Found 0 cases in 0 suites over 1 files.

  ✓ 0 cases failed.

  ⚠ Couldn't import 1 files:
    - /home/pinage404/Project/nix-sandboxes/nix/tests/hello.test.nix
      Command failed: nix eval --json --impure  --expr 'import /nix/store/08lsh2ydkxfp5hsx40vs9rd9bf86vjfa-nixt-0.2.2/lib/node_modules/nixt/nix/get-testspec.nix { path = "/home/pinage404/Project/nix-sandboxes/nix/tests/hello.test.nix"; }'
      error: undefined variable 'hello'
      
             at /home/pinage404/Project/nix-sandboxes/nix/tests/hello.test.nix:5:15:
      
                  4|   "Hello" = {
                  5|     "world" = hello == "Hello world";
                   |               ^
                  6|   };
      

everything is good
```

`everything is good` is outputed, so `nixt` returns a `0` code

Maybe it's because there is a compilation error

So, i also tested with a valid program that fails

```nix
{ nixt }:

let
  hello = "Hello anything but world";
in

nixt.mkSuites {
  "Hello" = {
    "world" = hello == "Hello world";
  };
}
```

```sh
nixt tests && echo "everything is good" || echo "something is bad"
```

```
Found 1 cases in 1 suites over 1 files.

  ✗ 1 cases failed.

┏ /home/pinage404/Project/nix-sandboxes/nix/tests/hello.test.nix
┃   Hello
┗     ✗ world


everything is good
```

But there is still the same issue

**Comment by pinage404** [comment]
I [made a script](https://gitlab.com/pinage404/nix-sandboxes/-/blob/795b75d81d737d19490c14b970440d0ad61fd007/nix/nixt) to work around this problem

```sh
#!/usr/bin/env bash
TEST_OUTPUT=$(nixt "$*")
echo "${TEST_OUTPUT}"
[[ ! "${TEST_OUTPUT}" =~ '✗' ]] && [[ ! "${TEST_OUTPUT}" =~ '⚠' ]]
```

**Comment by pinage404** [comment]
Hello,

I've [updated Nixt to the last version](https://gitlab.com/pinage404/nix-sandboxes/-/blob/71d417aea2d3bc08e23ab2866ca988fe60c72372/nix/flake.lock#L75)

But it still returns a 0 code when [a test fail](https://gitlab.com/pinage404/nix-sandboxes/-/blob/71d417aea2d3bc08e23ab2866ca988fe60c72372/nix/tests/hello.test.nix)

What am I doing wrong @Lord-Valen ?

**Comment by Lord-Valen** [comment]
Seems like when I refactored for inversify I forgot to set the exit code on error. It should still return non-zero on import failure.
