### ISSUE TITLE
Doesn't find any tests

### ISSUE THREAD

**Issue by gilligan** [nix-community/nixt#2]
I wanted to give nixt a try but i can't seem to get it to work. I quickly uploaded a small reproducer here: https://github.com/gilligan/nixt-issue

```
$ nix-shell
$ nixt ./tests/
Found 0 test suites

🎉 0 tests PASSED 🎉
```

It's not clear to me what the problem is here. I played around with the functions in `nix/utils.nix` and it does find the file and `isTestSuite` does say it is a test so maybe the problem is in the nim code? I don't know. Maybe you can have a look?

Would love to try out nixt.

**Comment by jlesquembre** [comment]
I was having the same error, looks like the path to your tests need to be absolute, e.g.:

```
nixt `pwd`/tests
```

**Comment by dustinlacewell** [comment]
Hello, thanks for trying Nixt. Sorry for the delay.

Can you try the new Typescript rewrite?

https://github.com/nix-community/nixt/tree/typescript-rewrite

It should support relative paths!

**Comment by Lord-Valen** [comment]
I cannot reproduce this issue.
