### ISSUE TITLE
README.md contian invalid code examples 

### ISSUE THREAD

**Issue by adrian-gierakowski** [nix-community/nixt#36]
for example:

![image](https://user-images.githubusercontent.com/330177/233040965-abf5d7fc-d828-455f-975c-ad63faf578b8.png)

I guess it should be:

```nix
{nixt, pkgs ? import <nixpkgs> {}}:

nixt.block ./block.spec.nix [
  (describe' "nixt" [
    ["passes this test" true]
    ["fails this test" false]
  ])
]
```

**Comment by Lord-Valen** [comment]
Oops! This should be
```nix
{
  nixt,
  pkgs ? import <nixpkgs> {},
}: nixt.block ./block.spec.nix [
  (nixt.describe' "nixt" {
  	"passes this test" = true;
    "fails this test" = false;
  })
]
```
The purpose of the `'` variants is to allow users to use attrsets (which I find more comfortable to write) instead of lists at whichever level they please.
